import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { createHandlerBoundToURL } from 'workbox-precaching';

// 1. Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// 2. SPA Navigation Fallback
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler, {
    denylist: [/^\/api\//],
});
registerRoute(navigationRoute);

// 3. Runtime Caching (Mirrors previous generateSW config)
registerRoute(
    /\/api\/leads/,
    new NetworkFirst({
        cacheName: 'leads-api-cache',
        plugins: [
            new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 86400 }),
            new CacheableResponsePlugin({ statuses: [0, 200] }),
        ],
        networkTimeoutSeconds: 5,
    })
);

registerRoute(
    /\/api\/lms\//,
    new StaleWhileRevalidate({
        cacheName: 'lms-content-cache',
        plugins: [
            new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 604800 }),
            new CacheableResponsePlugin({ statuses: [0, 200] }),
        ],
    })
);

registerRoute(
    /\/api\/dashboard/,
    new NetworkFirst({
        cacheName: 'dashboard-cache',
        plugins: [new ExpirationPlugin({ maxAgeSeconds: 300 })],
        networkTimeoutSeconds: 3,
    })
);

registerRoute(
    /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
    new CacheFirst({
        cacheName: 'image-cache',
        plugins: [new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 2592000 })],
    })
);

// 4. Custom Push Notification Logic
self.addEventListener('push', function (event) {
    if (!event.data) return;

    try {
        const payload = event.data.json();
        let title = 'CRM Notification';
        let body = 'You have a new message.';
        let data = { url: '/' };
        
        if (payload.notification) {
            title = payload.notification.title || title;
            body = payload.notification.body || body;
        }
        if (payload.data) {
            data = payload.data;
        }
        
        const options = {
            body: body,
            icon: '/favicon.svg',
            badge: '/favicon.svg',
            data: data,
            requireInteraction: true
        };
        
        event.waitUntil(self.registration.showNotification(title, options));
    } catch (err) {
        console.error('Push error:', err);
    }
});

self.addEventListener('notificationclick', function(event) {
    event.notification.close();
    const data = event.notification.data || {};
    const urlToOpen = new URL(data.url || '/', self.location.origin).href;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen) return client.focus();
            }
            return clients.openWindow(urlToOpen);
        })
    );
});
